#!/usr/bin/env bash

echo USE AT YOUR OWN RISK
echo
echo About to delete all images containing the string "eve-service-gateway"
read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker image rm -f $(docker image ls --format="{{.Repository}}:{{.Tag}}" | grep eve-service-gateway)
fi
